version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - app-tier
    command:
      tail -f /dev/null
    env_file:
      - .env
  db:
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: # PASSWORD
      POSTGRES_DB: # DB
      POSTGRES_USER: # USER
    ports:
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres_setup/database_initialization.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-tier:
    driver: bridge